refactor(core): avoid object creation in bind
mhevery/angular pull request #20
Opened 2017-12-18 21:07 UTC by kara

Implementing optimization @mhevery and I talked about last week to avoid creating unnecessary objects (causes GC pressure). 

Notes: 

- Review only last commit. 

- To avoid unnecessary addition operations (which may be slower on mobile), the indices are saved once they are calculated. This adds to code size, but shouldn't have significant impact once minified.

2017-12-18 21:53 UTC, pkozlowski-opensource commented
The change LGTM, but I would like to better understand this part:

>  to avoid creating unnecessary objects (causes GC pressure).

If I'm reading the code correctly, this is about creation mode, right? We are avoiding creating an object that would store old values (ex. `data[bindingIndex++] = {v0: v0, v1: v1};`). But at the same time we are creating more entries (elements) in the `data` array (a separate entry for each and every "old value"). Provided that I got the intention right, we are trading object creation for entries in array creation?

2017-12-19 04:49 UTC, mhevery commented
So each object has an overhead 56 bytes plus any properties stored an it. So moving from object to Array saves 56 bytes per binding. (This is because we already payed the array overhead).

There is an additional benefit in that when reading location `x` in array we will cause a cache fetch which means that  `x+1` read will most likely result in cache hit. So we get benefit of locality. We also save the cost of dereferencing through an un-needed object.

2017-12-19 04:54 UTC, mhevery requested changes

2017-12-19 04:54 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +    const part0 = data[part0Index];
I would inline the `++` as `data[bindingIndex++]`. This saves the creation of local war. (See next comment)

2017-12-19 04:54 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +      data[part0Index] = v0;
here just do `data[bingIndex - 2]` since stores are rare, this is fine

2017-12-19 21:11 UTC, kara commented
@mhevery  Should be ready

2017-12-23 00:49 UTC, kara commented
Closed in favor of https://github.com/angular/angular/pull/21155

2017-12-23 00:49 UTC, closed without merging