feat(core): more read options for ngIvy queries
mhevery/angular pull request #21
Opened 2017-12-19 15:55 UTC by pkozlowski-opensource

More fun with the `read` option for queries. TBH I didn't know if / how all the cases described in the test work today... 

I'm not sure if storage option for local names under which a directive is exported (`<div #foo="directive">` is the best - please have a look at the proposed `NG_LOCALNAME_SYMBOL`.

Unfortunately I've got a longish list of more corner cases I can think of, so stay tuned for more PRs like this...

2017-12-19 19:34 UTC, mhevery requested changes

2017-12-19 19:34 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +      Object.defineProperty(directive, NG_LOCALNAME_SYMBOL, {enumerable: false, value: localName});
this is a slow operation and one which is megamorphic. We need to solve this in a way which does not require monkey patching.

2017-12-19 19:34 UTC, mhevery commented on packages/core/src/render3/query.ts
> +    if (instance[NG_LOCALNAME_SYMBOL] === selector) {
this is a megamorphic read, hence slow. Need to solve it differently. We probably need to store it on the staticData

2017-12-20 10:38 UTC, pkozlowski-opensource commented
@mhevery updated to use a different storage option as described in https://github.com/mhevery/angular/pull/21/files#diff-5505b78967166511d61d5d2acbbe454aR60

PTAL

2017-12-21 05:39 UTC, mhevery approved these changes

2017-12-21 09:18 UTC, pkozlowski-opensource commented
@mhevery rebased, should be good to go in.

2017-12-27 18:21 UTC, mhevery approved these changes

2017-12-27 18:25 UTC, mhevery commented
closing in favor of https://github.com/angular/angular/pull/21187

2017-12-27 18:25 UTC, closed without merging